### ISSUE TITLE
Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by dalekcoffee** [Horhik/Instagram2Fedi#22]
Hello!

I have just deployed via docker

Under the instagram variable I have attempted a few accounts including my own without luck
When the container runs I always get 

JSON Query to justdalek_/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

Is there something that I need to change to resolve this error message?

**Comment by dalekcoffee** [comment]
2023-10-03 17:42:03 JSON Query to justdalek_/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
2023-10-03 17:42:04 JSON Query to justdalek_/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
2023-10-03 17:42:06 instagram justdalek_
2023-10-03 17:42:06 instagram test.justdalek.com
2023-10-03 17:42:06 CENSORED_KEY
2023-10-03 17:42:06 3600
2023-10-03 17:42:06 3600
2023-10-03 17:42:06 4
2023-10-03 17:42:06 5
2023-10-03 17:42:06 ['/app/src/main.py']
2023-10-03 17:42:06 ARGUMENTS
2023-10-03 17:42:06 {'instance': 'test.justdalek.com', 'instagram-user': 'justdalek_', 'token': 'CENSORED_KEY', 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 5, 'carousel-limit': 4}
2023-10-03 17:42:06 FAIL ♂ SETTINGS {'instance': 'test.justdalek.com', 'instagram-user': 'justdalek_', 'token': 'CENSORED_KEY', 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 5, 'carousel-limit': 4}
2023-10-03 17:42:06 🚀 > Connecting to Mastodon/Pixelfed...
2023-10-03 17:42:06 
2023-10-03 17:42:06 2023-10-03 22:37:03.004496
2023-10-03 17:42:06 🚀 > Connecting to Instagram...
2023-10-03 17:42:06 
2023-10-03 17:42:06 2023-10-03 22:42:03.115711
2023-10-03 17:42:06 Traceback (most recent call last):
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
2023-10-03 17:42:06     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
2023-10-03 17:42:06 instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
2023-10-03 17:42:06 
2023-10-03 17:42:06 During handling of the above exception, another exception occurred:
2023-10-03 17:42:06 
2023-10-03 17:42:06 Traceback (most recent call last):
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
2023-10-03 17:42:06     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
2023-10-03 17:42:06 instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
2023-10-03 17:42:06 
2023-10-03 17:42:06 During handling of the above exception, another exception occurred:
2023-10-03 17:42:06 
2023-10-03 17:42:06 Traceback (most recent call last):
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
2023-10-03 17:42:06     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
2023-10-03 17:42:06 instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
2023-10-03 17:42:06 
2023-10-03 17:42:06 The above exception was the direct cause of the following exception:
2023-10-03 17:42:06 
2023-10-03 17:42:06 Traceback (most recent call last):
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 690, in _obtain_metadata
2023-10-03 17:42:06     metadata = self._context.get_json('{}/feed/'.format(self.username), params={})
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
2023-10-03 17:42:06     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
2023-10-03 17:42:06     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 382, in get_json
2023-10-03 17:42:06     raise QueryReturnedNotFoundException(error_string) from err
2023-10-03 17:42:06 instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to justdalek_/feed/: Could not find "window._sharedData" in html response.
2023-10-03 17:42:06 
2023-10-03 17:42:06 The above exception was the direct cause of the following exception:
2023-10-03 17:42:06 
2023-10-03 17:42:06 Traceback (most recent call last):
2023-10-03 17:42:06   File "/app/src/main.py", line 65, in <module>
2023-10-03 17:42:06     get_new_posts(mastodon, mastodon_carousel_size, post_limit, id_filename, using_mastodon, mastodon_carousel_size, post_interval, fetched_user)
2023-10-03 17:42:06   File "/app/src/network.py", line 77, in get_new_posts
2023-10-03 17:42:06     profile = get_instagram_user(fetched_user)
2023-10-03 17:42:06   File "/app/src/network.py", line 18, in get_instagram_user
2023-10-03 17:42:06     return Profile.from_username(L.context, user)
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 635, in from_username
2023-10-03 17:42:06     profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
2023-10-03 17:42:06   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 697, in _obtain_metadata
2023-10-03 17:42:06     raise ProfileNotExistsException('Profile {} does not exist.\nThe most similar profile{}: {}.'
2023-10-03 17:42:06 instaloader.exceptions.ProfileNotExistsException: Profile justdalek_ does not exist.
2023-10-03 17:42:06 The most similar profiles are: justdalek_, just.dalek, justdalek, tennantized.

**Comment by dalekcoffee** [comment]
I see it says my profile does not exist but I can see it here

<img width="73" alt="image" src="https://github.com/Horhik/Instagram2Fedi/assets/78516780/bc790670-3a2c-4b3d-8529-635f2d38e445">

Attempting profile name: memes
<img width="489" alt="image" src="https://github.com/Horhik/Instagram2Fedi/assets/78516780/24e9a975-2520-459e-9722-bc8bce60d131">

2023-10-03 17:47:26 Traceback (most recent call last):
2023-10-03 17:47:26   File "/app/src/main.py", line 65, in <module>
2023-10-03 17:47:26     get_new_posts(mastodon, mastodon_carousel_size, post_limit, id_filename, using_mastodon, mastodon_carousel_size, post_interval, fetched_user)
2023-10-03 17:47:26   File "/app/src/network.py", line 77, in get_new_posts
2023-10-03 17:47:26     profile = get_instagram_user(fetched_user)
2023-10-03 17:47:26   File "/app/src/network.py", line 18, in get_instagram_user
2023-10-03 17:47:26     return Profile.from_username(L.context, user)
2023-10-03 17:47:26   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 635, in from_username
2023-10-03 17:47:26     profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
2023-10-03 17:47:26   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 697, in _obtain_metadata
2023-10-03 17:47:26     raise ProfileNotExistsException('Profile {} does not exist.\nThe most similar profile{}: {}.'
2023-10-03 17:47:26 instaloader.exceptions.ProfileNotExistsException: Profile memes does not exist.
2023-10-03 17:47:26 The most similar profiles are: memes, meme.ig, memezar, ight, 6.memes.9.

**Comment by TalosSources** [comment]
Hi! I have the same issue. Did you find a solution?

**Comment by saxnot** [comment]
Instagram2Fedi is currently broken. I tried with a new mastodon account and a new instagram account and got the same error

```
[+] Running 2/2
 ✔ Network broomi_default  Created                                                        0.1s 
 ✔ Container broomi-bot-1  Created                                                        0.2s 
Attaching to bot-1
bot-1  | JSON Query to braunschweiger_broomicorns/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
bot-1  | JSON Query to braunschweiger_broomicorns/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
bot-1  | JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
bot-1  | JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
bot-1  | instagram braunschweiger_broomicorns
bot-1  | instagram https://mastodon.social#<Mastodon or pixelfed instance>
bot-1  | G2_-fHIDDENhiddenHIDDENhiddenHIDDENhiddenHIDDEN
bot-1  | 3600
bot-1  | 3600
bot-1  | 4
bot-1  | 5
bot-1  | ['/app/src/main.py']
bot-1  | ARGUMENTS
bot-1  | {'instance': 'https://mastodon.social#<Mastodon or pixelfed instance>', 'instagram-user': 'braunschweiger_broomicorns', 'token': 'G2_-fHIDDENhiddenHIDDENhiddenHIDDENhiddenHIDDEN', 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 5, 'carousel-limit': 4}
bot-1  | FAIL ♂ SETTINGS {'instance': 'https://mastodon.social#<Mastodon or pixelfed instance>', 'instagram-user': 'braunschweiger_broomicorns', 'token': 'G2_-fHIDDENhiddenHIDDENhiddenHIDDENhiddenHIDDEN', 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 5, 'carousel-limit': 4}
bot-1  | 🚀 > Connecting to Mastodon/Pixelfed...
bot-1  | 
bot-1  | 2026-02-21 09:46:38.879909
bot-1  | 🚀 > Connecting to Instagram...
bot-1  | 
bot-1  | 2026-02-21 09:46:39.009309
bot-1  |     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
bot-1  | instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
bot-1  | 
bot-1  | During handling of the above exception, another exception occurred:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
bot-1  |     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
bot-1  | instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
bot-1  | 
bot-1  | During handling of the above exception, another exception occurred:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
bot-1  |     raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
bot-1  | instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.
bot-1  | 
bot-1  | The above exception was the direct cause of the following exception:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 690, in _obtain_metadata
bot-1  |     metadata = self._context.get_json('{}/feed/'.format(self.username), params={})
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
bot-1  |     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
bot-1  |     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 382, in get_json
bot-1  |     raise QueryReturnedNotFoundException(error_string) from err
bot-1  | instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to braunschweiger_broomicorns/feed/: Could not find "window._sharedData" in html response.
bot-1  | 
bot-1  | During handling of the above exception, another exception occurred:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 351, in get_json
bot-1  |     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
bot-1  | instaloader.exceptions.ConnectionException: HTTP error code 401.
bot-1  | 
bot-1  | During handling of the above exception, another exception occurred:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 351, in get_json
bot-1  |     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
bot-1  | instaloader.exceptions.ConnectionException: HTTP error code 401.
bot-1  | 
bot-1  | During handling of the above exception, another exception occurred:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 351, in get_json
bot-1  |     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
bot-1  | instaloader.exceptions.ConnectionException: HTTP error code 401.
bot-1  | 
bot-1  | The above exception was the direct cause of the following exception:
bot-1  | 
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/src/main.py", line 65, in <module>
bot-1  |     get_new_posts(mastodon, mastodon_carousel_size, post_limit, id_filename, using_mastodon, mastodon_carousel_size, post_interval, fetched_user)
bot-1  |   File "/app/src/network.py", line 77, in get_new_posts
bot-1  |     profile = get_instagram_user(fetched_user)
bot-1  |   File "/app/src/network.py", line 18, in get_instagram_user
bot-1  |     return Profile.from_username(L.context, user)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 635, in from_username
bot-1  |     profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 694, in _obtain_metadata
bot-1  |     top_search_results = TopSearchResults(self._context, self.username)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 1523, in __init__
bot-1  |     self._node = context.get_json('web/search/topsearch/',
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
bot-1  |     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
bot-1  |     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
bot-1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 384, in get_json
bot-1  |     raise ConnectionException(error_string) from err
bot-1  | instaloader.exceptions.ConnectionException: JSON Query to web/search/topsearch/: HTTP error code 401.
bot-1 exited with code 1
```
with
```
docker-compose.yaml 
services:
  bot:
    build:
      context: .
    image: "horhik/instagram2fedi:latest"
    environment:
      - YOUR_CONTAINER_NAME=instagram2fedi
      - I2M_INSTAGRAM_USER=braunschweiger_broomicorns #<fetched instagram user name>
      - I2M_INSTANCE=https://mastodon.social#<Mastodon or pixelfed instance>
      - I2M_TOKEN=G2_-fDaCM57jbMFL4whiddenHIDDENhiddenHIDDEN # SECRET TOKEN
      - I2M_CHECK_INTERVAL=3600 #1 hour    
      - I2M_POST_INTERVAL=3600 #1 hour   
      - I2M_USE_MASTODON=4 #max carouse    - is 4, if there's no limit set to -1
      - I2M_FETCH_COUNT=5 # how many instagram posts to fetch per check_interval   -
      - I2M_USER_NAME=ulz8rnoga8c@temp.mailbox.org # Your instagram login name
      - I2M_USER_PASSWORD=M7AfdHKjWrVjzrDSkhzAhiddenHIDDENhidden # Your instagram password
```

All credentials are already revoked and partially hidden to show it was not left blank.

**Comment by dalekcoffee** [comment]
This program was last updated 3 years ago I think it says? this was abandoned idk I gave up on it long ago
