### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by alex-ash** [Horhik/Instagram2Fedi#6]
Here, what logs look like after release:

```
2022-05-12T20:31:33.561030+00:00 heroku[web.1]: Starting process with command `python /app/src/main.py`
2022-05-12T20:31:34.577497+00:00 app[web.1]: ['/app/src/main.py', 'python', '/app/src/main.py']
2022-05-12T20:31:34.577514+00:00 app[web.1]: ARGUMENTS
2022-05-12T20:31:34.577514+00:00 app[web.1]: ❗ -> Wrong Argument Name!...
2022-05-12T20:31:34.577514+00:00 app[web.1]: 
2022-05-12T20:31:34.577515+00:00 app[web.1]: 2022-05-12 20:31:34.576732
2022-05-12T20:31:34.577524+00:00 app[web.1]: {'instance': None, 'instagram-user': None, 'token': None, 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 10, 'carousel-limit': 4, 'use-docker': True}
2022-05-12T20:31:34.577525+00:00 app[web.1]: 🚀 > Connecting to Mastodon/Pixelfed...
2022-05-12T20:31:34.577525+00:00 app[web.1]: 
2022-05-12T20:31:34.577525+00:00 app[web.1]: 2022-05-12 20:31:34.576844
2022-05-12T20:31:34.577525+00:00 app[web.1]: 🚀 > Connecting to Instagram...
2022-05-12T20:31:34.577526+00:00 app[web.1]: 
2022-05-12T20:31:34.577526+00:00 app[web.1]: 2022-05-12 20:31:34.577390
2022-05-12T20:31:34.577531+00:00 app[web.1]: Traceback (most recent call last):
2022-05-12T20:31:34.577532+00:00 app[web.1]: File "/app/src/main.py", line 66, in <module>
2022-05-12T20:31:34.577645+00:00 app[web.1]: get_new_posts(mastodon, mastodon_carousel_size, post_limit, id_filename, using_mastodon, mastodon_carousel_size, post_interval, fetched_user)
2022-05-12T20:31:34.577647+00:00 app[web.1]: File "/app/src/network.py", line 77, in get_new_posts
2022-05-12T20:31:34.577744+00:00 app[web.1]: profile = get_instagram_user(fetched_user)
2022-05-12T20:31:34.577746+00:00 app[web.1]: File "/app/src/network.py", line 18, in get_instagram_user
2022-05-12T20:31:34.577817+00:00 app[web.1]: return Profile.from_username(L.context, user)
2022-05-12T20:31:34.577819+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 691, in from_username
2022-05-12T20:31:34.578018+00:00 app[web.1]: profile = cls(context, {'username': username.lower()})
2022-05-12T20:31:34.578033+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lower'
2022-05-12T20:31:34.742759+00:00 heroku[web.1]: Process exited with status 1
2022-05-12T20:31:34.852473+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-12T20:31:34.889132+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-12T20:31:46.309290+00:00 heroku[web.1]: Starting process with command `python /app/src/main.py`
2022-05-12T20:31:47.285607+00:00 app[web.1]: ['/app/src/main.py', 'python', '/app/src/main.py']
2022-05-12T20:31:47.285619+00:00 app[web.1]: ARGUMENTS
2022-05-12T20:31:47.285620+00:00 app[web.1]: ❗ -> Wrong Argument Name!...
2022-05-12T20:31:47.285620+00:00 app[web.1]: 
2022-05-12T20:31:47.285620+00:00 app[web.1]: 2022-05-12 20:31:47.284780
2022-05-12T20:31:47.286053+00:00 app[web.1]: {'instance': None, 'instagram-user': None, 'token': None, 'check-interval': 3600, 'post-interval': 3600, 'fetch-count': 10, 'carousel-limit': 4, 'use-docker': True}
2022-05-12T20:31:47.286054+00:00 app[web.1]: 🚀 > Connecting to Mastodon/Pixelfed...
2022-05-12T20:31:47.286054+00:00 app[web.1]: 
2022-05-12T20:31:47.286054+00:00 app[web.1]: 2022-05-12 20:31:47.284902
2022-05-12T20:31:47.286055+00:00 app[web.1]: 🚀 > Connecting to Instagram...
2022-05-12T20:31:47.286055+00:00 app[web.1]: 
2022-05-12T20:31:47.286055+00:00 app[web.1]: 2022-05-12 20:31:47.285511
2022-05-12T20:31:47.286063+00:00 app[web.1]: Traceback (most recent call last):
2022-05-12T20:31:47.286063+00:00 app[web.1]: File "/app/src/main.py", line 66, in <module>
2022-05-12T20:31:47.286064+00:00 app[web.1]: get_new_posts(mastodon, mastodon_carousel_size, post_limit, id_filename, using_mastodon, mastodon_carousel_size, post_interval, fetched_user)
2022-05-12T20:31:47.286064+00:00 app[web.1]: File "/app/src/network.py", line 77, in get_new_posts
2022-05-12T20:31:47.286064+00:00 app[web.1]: profile = get_instagram_user(fetched_user)
2022-05-12T20:31:47.286065+00:00 app[web.1]: File "/app/src/network.py", line 18, in get_instagram_user
2022-05-12T20:31:47.286065+00:00 app[web.1]: return Profile.from_username(L.context, user)
2022-05-12T20:31:47.286067+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 691, in from_username
2022-05-12T20:31:47.286093+00:00 app[web.1]: profile = cls(context, {'username': username.lower()})
2022-05-12T20:31:47.286114+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lower'
2022-05-12T20:31:47.451100+00:00 heroku[web.1]: Process exited with status 1
2022-05-12T20:31:47.494216+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by Horhik** [comment]
Are you using it with docker-compose?
You're missing several environment variables

**Comment by alex-ash** [comment]
Yes. And with variables in env.sh
<img width="842" alt="image" src="https://user-images.githubusercontent.com/75944559/168244755-e03b94e3-3c38-4c07-9b2f-cf9962a03eec.png">

**Comment by Horhik** [comment]
Hmmm.... Try to remove `build: context .`
And... hide your token :)
I think now u should recreate it for  your own security

**Comment by alex-ash** [comment]
The token is totally safe, it's not even a half of it. :)
Tried without `build: context .I`

In local docker everything runs like a charm and every variable is in the right place. As for Heroku – same result. Variables lost somewhere. I already deleted the entire app on Heroku and re-deployed it, and nothing changed.

**Comment by Horhik** [comment]
Hmm... strange..
You can try to run it without docker :)
https://github.com/Horhik/Instagram2Fedi/blob/main/Docs.md

Maybe you should try to specify an .env file in compose file `env_file: .env`

**Comment by alex-ash** [comment]
Maybe it's because Heroku uses only src/main.py file. All errors come from it. And there are no arguments by default.


<img width="705" alt="image" src="https://user-images.githubusercontent.com/75944559/168339960-6be4c637-dfa8-4a49-8960-7c5750e3bf33.png">

**Comment by alex-ash** [comment]
I was right. Somehow, Heroku uses variables only from main.py.
The question is how to fix this.

**Comment by alex-ash** [comment]
Maybe it's all about python version, idk.

**Comment by Horhik** [comment]
I think there's a problem in how do you set up docker with heroku. 
https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

**Comment by alex-ash** [comment]
Yeah. Since i'm no programmer at all, any help with heroku.yml?

**Comment by alex-ash** [comment]
UPD
It seems Heroku uses only its own configured variables, not env.sh. But still, after I define them arguments.py doesn't work and returns `❗ -> Wrong Argument Name!...`

Vars from docker-compose are ignored as well.

**Comment by Horhik** [comment]
@alex-ash Wrong argument Name means what you made a typo or incorrect input.

You can pass your arguments not only with docker but with command line flags. Then you don't even need docker :)
 
![Screenshot from 2022-05-14 10-14-59](https://user-images.githubusercontent.com/46262811/168415295-98f471f7-7e4d-4d32-a155-9b588bacfb9b.png)
 
 try to:
 ``` bash
python -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt
./insta2fedi --use-docker false --instagram-user dalsfkjsdl --instance sdfkljhsdlfkjsdf --token asfsfasdfssdfsadfsdfs --check-interval 10 --post-interval 10 --use-mastodon 4
```

**Comment by alex-ash** [comment]
There are no errors in arguments on local docker. I will try tho. thank you so much.

**Comment by alex-ash** [comment]
Okay, I've made huge progress!

Here's news. Heroku needs a Procfile where run.sh is specified. In run.sh it found a syntax error:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/75944559/168441774-cb4717a9-a2e2-4a11-9504-288b3d218114.png">

So I deleted / and env was successfully imported. After that, I encountered new syntax errors in other commands in run.sh.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/75944559/168441879-53995d8b-a0a2-4bb3-88c2-b76fb4dbb155.png">

And so on. After we finish this, I promise, you'll be able to add complete heroku instructions into your docs.
Any suggestions about syntax in run.sh?

**Comment by Horhik** [comment]
Damn.... you're running bash file via python interpreter... obviously it will completely consist of syntax errors
